version: '3.7'

x-default-opts:
  &default-opts
  logging:
    options:
      max-size: "10m"

networks:
  ntw_front:
    external: true
  portainer:
    driver: overlay

volumes:
  portainer_data:

services:

  portainer:
    <<: *default-opts
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    #managed by Traefik
    #ports:
    #  - "9000:9000"
    volumes:
      - portainer_data:/data
    networks:
      - ntw_front
      - portainer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.20'
          memory: 48M
        reservations:
          memory: 4M
      labels:
        - "traefik.backend=portainer"
        - "traefik.frontend.rule=PathPrefixStrip:/portainer"
        - "traefik.port=9000"
        - "traefik.enable=true"
        - "traefik.docker.network=ntw_front"
        - "traefik.weight=10"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend.loadbalancer.method=drr"
        ## Bug fix / https://github.com/containous/traefik/issues/563#issuecomment-421360934
        - "traefik.frontend.redirect.regex=^(.*)/portainer$$"
        - "traefik.frontend.redirect.replacement=$$1/portainer/"
        - "traefik.frontend.rule=PathPrefix:/portainer;ReplacePathRegex: ^/portainer/(.*) /$$1"

  agent:
    <<: *default-opts
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.20'
          memory: 48M
        reservations:
          memory: 4M

# https://github.com/pascalandy/docker-stack-this